using UnityEngine;

[RequireComponent(typeof(CharacterController))]
public sealed class PlayerMovementController : MonoBehaviour
{
    [Header("Movement")]
    [Tooltip("Normal movement speed in meters per second.")]
    [SerializeField, Min(0f)] private float walkSpeed = 5f;

    [Tooltip("Movement speed while sprinting.")]
    [SerializeField, Min(0f)] private float sprintSpeed = 8f;

    [Tooltip("Key used to sprint.")]
    [SerializeField] private KeyCode sprintKey = KeyCode.LeftShift;

    [Header("Jump")]
    [Tooltip("Maximum jump height in meters.")]
    [SerializeField, Min(0f)] private float jumpHeight = 1.5f;

    [Tooltip("Gravity acceleration. Must be negative.")]
    [SerializeField] private float gravity = -20f;

    [Tooltip(
        "Small downward velocity maintained while grounded. " +
        "Helps keep the CharacterController attached to the floor.")]
    [SerializeField] private float groundedVelocity = -2f;

    [Header("External Forces")]
    [Tooltip(
        "How quickly external velocity disappears when no force is being applied. " +
        "Higher values stop knockback/wind effects faster.")]
    [SerializeField, Min(0f)] private float externalVelocityDamping = 8f;

    [Tooltip(
        "Maximum external velocity allowed. " +
        "Prevents extreme external forces from producing unstable movement.")]
    [SerializeField, Min(0f)] private float maximumExternalSpeed = 20f;

    private CharacterController characterController;

    private float verticalVelocity;
    private Vector3 externalVelocity;

    /// <summary>
    /// True when the CharacterController is currently touching the ground.
    /// </summary>
    public bool IsGrounded =>
        characterController != null &&
        characterController.isGrounded;

    /// <summary>
    /// Final velocity applied to the CharacterController during the last frame.
    /// Includes player movement, gravity and external velocity.
    /// </summary>
    public Vector3 Velocity { get; private set; }

    /// <summary>
    /// Current velocity contributed by external systems
    /// such as fans, explosions or knockback.
    /// </summary>
    public Vector3 ExternalVelocity => externalVelocity;

    private void Awake()
    {
        characterController = GetComponent<CharacterController>();
    }

    private void Update()
    {
        HandleMovement();
    }

    private void HandleMovement()
    {
        bool isGrounded = characterController.isGrounded;

        HandleGrounding(isGrounded);

        Vector3 movementVelocity = CalculateMovementVelocity();

        HandleJump(isGrounded);

        ApplyGravity();

        /*
         * Base velocity generated by the player's own movement.
         */
        Vector3 playerVelocity = new Vector3(
            movementVelocity.x,
            verticalVelocity,
            movementVelocity.z
        );

        /*
         * ExternalVelocity is intentionally independent from player input.
         *
         * This allows external gameplay systems to push the Player
         * without directly manipulating the CharacterController.
         */
        Velocity =
            playerVelocity +
            externalVelocity;

        characterController.Move(
            Velocity * Time.deltaTime
        );

        UpdateExternalVelocity();
    }

    private void HandleGrounding(bool isGrounded)
    {
        /*
         * Prevent gravity from accumulating indefinitely while grounded.
         *
         * A small negative velocity helps the CharacterController remain
         * attached to floors and slopes.
         */
        if (isGrounded && verticalVelocity < 0f)
        {
            verticalVelocity = groundedVelocity;
        }
    }

    private Vector3 CalculateMovementVelocity()
    {
        float horizontalInput =
            Input.GetAxisRaw("Horizontal");

        float verticalInput =
            Input.GetAxisRaw("Vertical");

        Vector3 inputDirection = new Vector3(
            horizontalInput,
            0f,
            verticalInput
        );

        /*
         * Prevent diagonal input from being faster than straight movement.
         */
        inputDirection =
            Vector3.ClampMagnitude(
                inputDirection,
                1f
            );

        /*
         * Movement is relative to the Player orientation.
         *
         * The camera/look system can rotate the Player horizontally,
         * while this component remains completely unaware of cameras.
         */
        Vector3 movementDirection =
            transform.right * inputDirection.x +
            transform.forward * inputDirection.z;

        float currentSpeed =
            Input.GetKey(sprintKey)
                ? sprintSpeed
                : walkSpeed;

        return movementDirection * currentSpeed;
    }

    private void HandleJump(bool isGrounded)
    {
        if (!isGrounded)
        {
            return;
        }

        if (!Input.GetButtonDown("Jump"))
        {
            return;
        }

        /*
         * Calculate the upward velocity required to reach jumpHeight
         * under the configured gravity.
         */
        verticalVelocity =
            Mathf.Sqrt(
                jumpHeight *
                -2f *
                gravity
            );
    }

    private void ApplyGravity()
    {
        verticalVelocity +=
            gravity * Time.deltaTime;
    }

    private void UpdateExternalVelocity()
    {
        if (externalVelocity.sqrMagnitude <= Mathf.Epsilon)
        {
            externalVelocity = Vector3.zero;
            return;
        }

        /*
         * Gradually remove external velocity once external systems
         * stop adding to it.
         *
         * This produces a controllable residual push instead of an
         * instantaneous stop.
         */
        externalVelocity =
            Vector3.MoveTowards(
                externalVelocity,
                Vector3.zero,
                externalVelocityDamping *
                Time.deltaTime
            );
    }

    /// <summary>
    /// Adds velocity generated by an external gameplay source.
    ///
    /// Examples:
    /// fans, explosions, knockback, wind or moving machinery.
    /// </summary>
    public void AddExternalVelocity(Vector3 velocity)
    {
        externalVelocity += velocity;

        ClampExternalVelocity();
    }

    /// <summary>
    /// Replaces the current external velocity.
    /// </summary>
    public void SetExternalVelocity(Vector3 velocity)
    {
        externalVelocity = velocity;

        ClampExternalVelocity();
    }

    /// <summary>
    /// Immediately removes all external velocity.
    /// </summary>
    public void ClearExternalVelocity()
    {
        externalVelocity = Vector3.zero;
    }

    private void ClampExternalVelocity()
    {
        if (maximumExternalSpeed <= 0f)
        {
            externalVelocity = Vector3.zero;
            return;
        }

        externalVelocity =
            Vector3.ClampMagnitude(
                externalVelocity,
                maximumExternalSpeed
            );
    }

    private void OnValidate()
    {
        walkSpeed =
            Mathf.Max(
                0f,
                walkSpeed
            );

        sprintSpeed =
            Mathf.Max(
                0f,
                sprintSpeed
            );

        jumpHeight =
            Mathf.Max(
                0f,
                jumpHeight
            );

        externalVelocityDamping =
            Mathf.Max(
                0f,
                externalVelocityDamping
            );

        maximumExternalSpeed =
            Mathf.Max(
                0f,
                maximumExternalSpeed
            );

        /*
         * The jump calculation assumes downward gravity.
         */
        if (gravity >= 0f)
        {
            gravity = -0.01f;
        }

        if (groundedVelocity > 0f)
        {
            groundedVelocity = 0f;
        }
    }
}