using UnityEngine;

[RequireComponent(typeof(Collider))]
public sealed class FanWindZone : MonoBehaviour
{
    [Header("Wind")]
    [Tooltip("Base acceleration generated by the turbine.")]
    [SerializeField, Min(0f)] private float pushStrength = 20f;

    [Tooltip(
        "Wind direction expressed in local space. " +
        "For most turbines use Forward (0, 0, 1).")]
    [SerializeField] private Vector3 localWindDirection = Vector3.forward;

    [Tooltip(
        "Optional origin of the airflow. " +
        "Place it approximately at the center/front of the turbine.")]
    [SerializeField] private Transform windOrigin;

    [Header("Cone Shape")]
    [Tooltip("Radius of the airflow where it exits the turbine.")]
    [SerializeField, Min(0f)] private float startRadius = 1f;

    [Tooltip("Radius of the airflow at maximum distance.")]
    [SerializeField, Min(0f)] private float endRadius = 4f;

    [Tooltip("Maximum length of the wind cone.")]
    [SerializeField, Min(0.1f)] private float coneLength = 8f;

    [Header("Cone Falloff")]
    [Tooltip(
        "Controls how much strength remains at the end of the cone. " +
        "0 means no wind at maximum distance.")]
    [SerializeField, Range(0f, 1f)] private float endStrengthMultiplier = 0.1f;

    [Tooltip(
        "Controls how much wind remains at the outer edge of the cone. " +
        "0 means the edge has no force.")]
    [SerializeField, Range(0f, 1f)] private float edgeStrengthMultiplier = 0.15f;

    [Tooltip(
        "Exponent controlling longitudinal falloff. " +
        "1 = linear. Higher values keep wind stronger near the turbine.")]
    [SerializeField, Min(0.01f)] private float distanceFalloffPower = 1.5f;

    [Tooltip(
        "Exponent controlling radial falloff toward the cone edges.")]
    [SerializeField, Min(0.01f)] private float radialFalloffPower = 1.5f;

    [Header("Gusts")]
    [Tooltip("Enable cyclic turbine gusts.")]
    [SerializeField] private bool useGusts = true;

    [Tooltip("Minimum wind multiplier during the weak portion of a gust.")]
    [SerializeField, Min(0f)] private float minimumGustMultiplier = 0.2f;

    [Tooltip("Maximum wind multiplier during the strongest portion of a gust.")]
    [SerializeField, Min(0f)] private float maximumGustMultiplier = 1.25f;

    [Tooltip("Duration in seconds of one complete gust cycle.")]
    [SerializeField, Min(0.05f)] private float gustCycleDuration = 1.4f;

    [Tooltip(
        "Phase offset. Useful when multiple turbines should not pulse together.")]
    [SerializeField] private float gustPhaseOffset;

    [Header("Detection")]
    [Tooltip("Layers affected by this turbine.")]
    [SerializeField] private LayerMask affectedLayers;

    [Header("Debug")]
    [SerializeField] private bool drawDebugGizmos = true;

    [Tooltip("Number of segments used to visualize the cone.")]
    [SerializeField, Range(4, 32)] private int gizmoSegments = 16;

    private Collider triggerCollider;

    public float CurrentGust01 { get; private set; }
    public float CurrentGustMultiplier { get; private set; } = 1f;

    private void Awake()
    {
        triggerCollider = GetComponent<Collider>();

        if (!triggerCollider.isTrigger)
        {
            triggerCollider.isTrigger = true;

            Debug.LogWarning(
                $"{nameof(FanWindZone)} on '{gameObject.name}' requires " +
                "its Collider to be a Trigger. It was enabled automatically.",
                this
            );
        }

        if (windOrigin == null)
        {
            windOrigin = transform;
        }
    }

    private void Update()
    {
        UpdateGust();
    }

    private void OnTriggerStay(Collider other)
    {
        if (!IsLayerAffected(other.gameObject.layer))
        {
            return;
        }

        PlayerMovementController player =
            other.GetComponentInParent<PlayerMovementController>();

        if (player == null)
        {
            return;
        }

        ApplyWind(player);
    }

    private void ApplyWind(PlayerMovementController player)
    {
        Transform originTransform =
            windOrigin != null
                ? windOrigin
                : transform;

        Vector3 originPosition =
            originTransform.position;

        Vector3 windDirection =
            transform.TransformDirection(
                localWindDirection.normalized
            );

        Vector3 toPlayer =
            player.transform.position - originPosition;

        /*
         * Axial distance:
         *
         * How far forward the Player is along the turbine's wind axis.
         */
        float axialDistance =
            Vector3.Dot(
                toPlayer,
                windDirection
            );

        /*
         * Player is behind the turbine or beyond the end of the cone.
         */
        if (axialDistance < 0f ||
            axialDistance > coneLength)
        {
            return;
        }

        /*
         * Normalized position through the cone:
         *
         * 0 = turbine exit
         * 1 = end of wind cone
         */
        float distance01 =
            axialDistance / coneLength;

        /*
         * Cone radius expands progressively.
         */
        float radiusAtDistance =
            Mathf.Lerp(
                startRadius,
                endRadius,
                distance01
            );

        /*
         * Find the closest point on the center axis.
         */
        Vector3 axisPoint =
            originPosition +
            windDirection * axialDistance;

        /*
         * Radial distance from the center of the airflow.
         */
        float radialDistance =
            Vector3.Distance(
                player.transform.position,
                axisPoint
            );

        /*
         * Outside the cone.
         */
        if (radialDistance > radiusAtDistance)
        {
            return;
        }

        /*
         * ---------------------------------------------------------
         * DISTANCE FALLOFF
         * ---------------------------------------------------------
         *
         * Near turbine = 1
         * End of cone  = endStrengthMultiplier
         */
        float distanceFalloff01 =
            Mathf.Pow(
                distance01,
                distanceFalloffPower
            );

        float distanceMultiplier =
            Mathf.Lerp(
                1f,
                endStrengthMultiplier,
                distanceFalloff01
            );

        /*
         * ---------------------------------------------------------
         * RADIAL FALLOFF
         * ---------------------------------------------------------
         *
         * Center = 1
         * Edge   = edgeStrengthMultiplier
         */
        float radial01 =
            radiusAtDistance > Mathf.Epsilon
                ? radialDistance / radiusAtDistance
                : 0f;

        float radialFalloff01 =
            Mathf.Pow(
                radial01,
                radialFalloffPower
            );

        float radialMultiplier =
            Mathf.Lerp(
                1f,
                edgeStrengthMultiplier,
                radialFalloff01
            );

        /*
         * Combine all wind influences.
         */
        float finalStrength =
            pushStrength *
            distanceMultiplier *
            radialMultiplier *
            CurrentGustMultiplier;

        if (finalStrength <= 0f)
        {
            return;
        }

        /*
         * The CharacterController receives an incremental
         * external velocity each frame.
         */
        Vector3 velocityChange =
            windDirection *
            finalStrength *
            Time.deltaTime;

        player.AddExternalVelocity(
            velocityChange
        );
    }

    private void UpdateGust()
    {
        if (!useGusts)
        {
            CurrentGust01 = 1f;
            CurrentGustMultiplier = 1f;

            return;
        }

        float angularTime =
            (Time.time + gustPhaseOffset) *
            (Mathf.PI * 2f / gustCycleDuration);

        float sine =
            Mathf.Sin(angularTime);

        /*
         * Convert:
         *
         * -1..1
         *
         * into:
         *
         * 0..1
         */
        CurrentGust01 =
            (sine + 1f) * 0.5f;

        /*
         * Soften acceleration/deceleration of the gust.
         */
        CurrentGust01 =
            Mathf.SmoothStep(
                0f,
                1f,
                CurrentGust01
            );

        CurrentGustMultiplier =
            Mathf.Lerp(
                minimumGustMultiplier,
                maximumGustMultiplier,
                CurrentGust01
            );
    }

    private bool IsLayerAffected(int layer)
    {
        return
            (affectedLayers.value & (1 << layer)) != 0;
    }

    private void OnValidate()
    {
        pushStrength =
            Mathf.Max(
                0f,
                pushStrength
            );

        startRadius =
            Mathf.Max(
                0f,
                startRadius
            );

        endRadius =
            Mathf.Max(
                0f,
                endRadius
            );

        coneLength =
            Mathf.Max(
                0.1f,
                coneLength
            );

        distanceFalloffPower =
            Mathf.Max(
                0.01f,
                distanceFalloffPower
            );

        radialFalloffPower =
            Mathf.Max(
                0.01f,
                radialFalloffPower
            );

        minimumGustMultiplier =
            Mathf.Max(
                0f,
                minimumGustMultiplier
            );

        maximumGustMultiplier =
            Mathf.Max(
                minimumGustMultiplier,
                maximumGustMultiplier
            );

        gustCycleDuration =
            Mathf.Max(
                0.05f,
                gustCycleDuration
            );

        if (localWindDirection.sqrMagnitude <=
            Mathf.Epsilon)
        {
            localWindDirection =
                Vector3.forward;
        }
    }

    private void OnDrawGizmosSelected()
    {
        if (!drawDebugGizmos)
        {
            return;
        }

        Transform originTransform =
            windOrigin != null
                ? windOrigin
                : transform;

        Vector3 origin =
            originTransform.position;

        Vector3 direction =
            transform.TransformDirection(
                localWindDirection.normalized
            );

        /*
         * Create a stable pair of perpendicular vectors around
         * the wind axis for drawing the circular sections.
         */
        Vector3 right =
            Vector3.Cross(
                direction,
                Vector3.up
            );

        /*
         * Handle turbines pointing almost perfectly vertically.
         */
        if (right.sqrMagnitude < 0.001f)
        {
            right =
                Vector3.Cross(
                    direction,
                    Vector3.right
                );
        }

        right.Normalize();

        Vector3 up =
            Vector3.Cross(
                right,
                direction
            ).normalized;

        Vector3 endCenter =
            origin +
            direction * coneLength;

        DrawCircle(
            origin,
            right,
            up,
            startRadius
        );

        DrawCircle(
            endCenter,
            right,
            up,
            endRadius
        );

        /*
         * Draw cone side lines.
         */
        for (int i = 0; i < gizmoSegments; i++)
        {
            float angle =
                (i / (float)gizmoSegments) *
                Mathf.PI *
                2f;

            Vector3 radialDirection =
                right * Mathf.Cos(angle) +
                up * Mathf.Sin(angle);

            Vector3 startPoint =
                origin +
                radialDirection * startRadius;

            Vector3 endPoint =
                endCenter +
                radialDirection * endRadius;

            Gizmos.DrawLine(
                startPoint,
                endPoint
            );
        }

        /*
         * Center axis.
         */
        Gizmos.DrawLine(
            origin,
            endCenter
        );
    }

    private void DrawCircle(
        Vector3 center,
        Vector3 right,
        Vector3 up,
        float radius)
    {
        Vector3 previousPoint =
            center +
            right * radius;

        for (int i = 1; i <= gizmoSegments; i++)
        {
            float angle =
                (i / (float)gizmoSegments) *
                Mathf.PI *
                2f;

            Vector3 currentPoint =
                center +
                (right * Mathf.Cos(angle) +
                 up * Mathf.Sin(angle)) *
                radius;

            Gizmos.DrawLine(
                previousPoint,
                currentPoint
            );

            previousPoint =
                currentPoint;
        }
    }
}